### ISSUE TITLE
encoding issue while trying to download the package

### ISSUE THREAD

**Issue by KavyaGujjala** [Andolab/miNER#1]
C:\Users\kavya>pip install git+https://github.com/Andolab/miNER#egg=miNER
Collecting miNER from git+https://github.com/Andolab/miNER#egg=miNER
  Cloning https://github.com/Andolab/miNER to c:\users\kavya\appdata\local\temp\pip-build-k2sp5qfs\miner
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\kavya\AppData\Local\Temp\pip-build-k2sp5qfs\miNER\setup.py", line 5, in <module>
        readme = f.read()
      File "C:\Users\kavya\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 905: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\kavya\AppData\Local\Temp\pip-build-k2sp5qfs\miNER\
You are using pip version 9.0.3, however version 19.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by s14t284** [comment]
Could you tell me your python environment.
I think encoding is involved.
I don't use windows OS during February.
So, my answer seems to be late.

**Comment by KavyaGujjala** [comment]
Hi,
Thanks for the reply.

I tried change the encoding in the setup.py file and it worked.
I could install it then.
